export const urls = {
    createWebinar: 'webinars/save',
    getWebinar: 'webinars/get',
    deleteWebinar: 'webinars/delete/',
    adminLogin: 'login/admin',
    usersLogin: 'login/user',
    marketingManagerLogin: 'login/marketingmanager',
    usersSignup: 'signup/user',
    addToCart: 'cart/',
    deleteItem: 'cart/',
    updateQuantity: 'cart/quantity',
    getCartDetails: 'cart/',
    payment: 'payment',
    gettokendetails: 'gettokendetails',
    getOrders: 'orders',
    saveCategory: 'category',
    deleteCategory: 'category/',
    getCategories: 'category',
    saveWebinarTypes: 'webinarTypes',
    getWebinarTypes: 'webinarTypes',
    saveSpeaker: 'speakers',
    getSpeakers: 'speakers/',
    getUsers: 'users',
    updateSpeaker: 'speakers/',
    sendRequest: 'email/contactform',
    paySession: 'payment',
    orderUpdate: 'orderUpdate'
}